### ISSUE TITLE
Output non-tiling

### ISSUE THREAD

**Issue by mrmartin** [notwa/resynth#1]
Hi, and thanks a lot for porting this plugin out of GIMP!

The function produces textures which always tile horizontally (left matches with right), but not vertically (top doesn't match with bottom).

Any ideas why this is? I've looked through the code, and couldn't find anything different about width and height.

This is the tiled output, with default parameters:
![grass-input resynth](https://cloud.githubusercontent.com/assets/944542/19835595/da40588c-9e83-11e6-95eb-d017f027c5fc.png)

**Comment by mrmartin** [comment]
I've just confirmed that Resynthesizer in GIMP doesn't have this issue

**Comment by notwa** [comment]
thanks. I get this with -S1 now:
![tiled](https://cloud.githubusercontent.com/assets/1459466/19862046/0089235c-9f4c-11e6-861e-76e4004c9fd8.png)
